#include "facelivt/kernel_registry.hpp"
#include <algorithm>
#include <fstream>
#include <map>
#include <sstream>
#include <vector>

namespace facelivt {
namespace {
std::vector<std::string> split_tsv(const std::string& row) {
    std::vector<std::string> columns;
    std::stringstream stream(row);
    std::string column;
    while(std::getline(stream,column,'\t')) columns.push_back(std::move(column));
    return columns;
}

struct ManifestKernel {
    int arch=0;
    std::string cubin;
    std::string entry;
    int warps=4;
    int shared=0;
    int scratch_args=0;
};

bool supports(int target_arch,int gpu_arch) {
    // NVIDIA cubins are compatible within a compute-capability major version
    // when the cubin's minor version is no newer than the device's.
    return target_arch/10==gpu_arch/10 && target_arch%10<=gpu_arch%10;
}
}

KernelRegistry::~KernelRegistry(){
    for(auto& kv:kernels_) if(kv.second.module) cuModuleUnload(kv.second.module);
}

void KernelRegistry::load(const std::filesystem::path& manifest,int device_ordinal){
    if(!kernels_.empty()) throw std::runtime_error("kernel registry already loaded");
    cu_check(cuInit(0),"cuInit");
    CUdevice device;
    cu_check(cuDeviceGet(&device,device_ordinal),"cuDeviceGet");
    int major=0,minor=0;
    cu_check(cuDeviceGetAttribute(&major,CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR,device),"read GPU compute capability major");
    cu_check(cuDeviceGetAttribute(&minor,CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR,device),"read GPU compute capability minor");
    const int gpu_arch=major*10+minor;

    std::ifstream file(manifest);
    if(!file) throw std::runtime_error("cannot open kernel manifest: "+manifest.string());
    std::string line;
    if(!std::getline(file,line)) throw std::runtime_error("kernel manifest is empty: "+manifest.string());
    const bool has_arch_column=line.rfind("arch\t",0)==0;
    const auto base=manifest.parent_path();
    std::map<std::string,ManifestKernel> selected;
    std::map<std::string,int> selected_arch;
    std::vector<int> available_arches;
    while(std::getline(file,line)){
        if(line.empty()) continue;
        auto columns=split_tsv(line);
        ManifestKernel candidate;
        std::string alias;
        if(has_arch_column){
            if(columns.size()<7) throw std::runtime_error("invalid architecture kernel manifest row: "+line);
            candidate.arch=std::stoi(columns[0]);
            alias=columns[1];
            candidate.cubin=columns[2];
            candidate.entry=columns[3];
            candidate.warps=std::stoi(columns[4]);
            candidate.shared=std::stoi(columns[5]);
            candidate.scratch_args=std::stoi(columns[6]);
            available_arches.push_back(candidate.arch);
        } else {
            // Read pre-matrix manifests generated by the original local build.
            if(columns.size()<5) throw std::runtime_error("invalid kernel manifest row: "+line);
            candidate.arch=gpu_arch;
            alias=columns[0];
            candidate.cubin=columns[1];
            candidate.entry=columns[2];
            candidate.warps=std::stoi(columns[3]);
            candidate.shared=std::stoi(columns[4]);
            if(columns.size()>5) candidate.scratch_args=std::stoi(columns[5]);
        }
        if(candidate.scratch_args<0 || candidate.scratch_args>2)
            throw std::runtime_error("unsupported Triton scratch argument count for "+alias);
        if(candidate.warps<1 || candidate.warps>32 || candidate.shared<0)
            throw std::runtime_error("invalid launch metadata for "+alias);
        if(!supports(candidate.arch,gpu_arch)) continue;
        auto found=selected_arch.find(alias);
        if(found==selected_arch.end() || candidate.arch>found->second){
            selected_arch[alias]=candidate.arch;
            selected[alias]=std::move(candidate);
        }
    }

    if(selected.empty()){
        std::sort(available_arches.begin(),available_arches.end());
        available_arches.erase(std::unique(available_arches.begin(),available_arches.end()),available_arches.end());
        std::ostringstream message;
        message<<"no FaceLiVT kernels in "<<manifest.string()<<" support GPU sm_"<<gpu_arch;
        if(!available_arches.empty()){
            message<<"; packaged architectures:";
            for(int arch:available_arches) message<<" sm_"<<arch;
        }
        throw std::runtime_error(message.str());
    }

    try {
        for(const auto& [alias,kernel]:selected){
            auto cubin=(base/kernel.cubin).string();
            KernelInfo info;
            info.warps=kernel.warps;
            info.shared=kernel.shared;
            info.scratch_args=kernel.scratch_args;
            cu_check(cuModuleLoad(&info.module,cubin.c_str()),("cuModuleLoad "+cubin).c_str());
            try {
                cu_check(cuModuleGetFunction(&info.function,info.module,kernel.entry.c_str()),
                         ("cuModuleGetFunction "+alias).c_str());
            } catch(...) {
                cuModuleUnload(info.module);
                throw;
            }
            kernels_.emplace(alias,info);
        }
    } catch(...) {
        for(auto& [alias,info]:kernels_) if(info.module) cuModuleUnload(info.module);
        kernels_.clear();
        throw;
    }
}

const KernelInfo& KernelRegistry::get(const std::string& alias) const {
    auto it=kernels_.find(alias);
    if(it==kernels_.end()) throw std::runtime_error("missing Triton kernel: "+alias);
    return it->second;
}

void KernelRegistry::launch(const std::string& alias,unsigned gx,unsigned gy,unsigned gz,
                            std::span<void*> args,cudaStream_t stream) const {
    const auto& k=get(alias);
    CUdeviceptr scratch=0;
    std::vector<void*> params(args.begin(),args.end());
    for(int i=0;i<k.scratch_args;++i) params.push_back(&scratch);
    cu_check(cuLaunchKernel(k.function,gx,gy,gz,static_cast<unsigned>(k.warps*32),1,1,
                            static_cast<unsigned>(k.shared),reinterpret_cast<CUstream>(stream),params.data(),nullptr),
             ("launch "+alias).c_str());
}
}
